version: '3.9'

networks:
  todo:

services:
  database:
    hostname: db
    container_name: todo_db
    image: postgres:13.9-alpine
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: todo,keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 1s
      timeout: 1s
      retries: 20
    networks:
      todo:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: todo_keycloak
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "7000:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      todo: